version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    file_exists_bahavior: OVERWRITE   
hooks:
   AfterInstall:
     - location: scripts/install.sh
       timeout: 180    
file_exists_behavior: OVERWRITE
